# coding: utf-8

# flake8: noqa
"""
    Swagger Petstore - OpenAPI 3.0

    FINBOURNE Technology  # noqa: E501

    The version of the OpenAPI document: 1.0.5
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from tests.sdk.petstore.models.address import Address
from tests.sdk.petstore.models.api_response import ApiResponse
from tests.sdk.petstore.models.category import Category
from tests.sdk.petstore.models.customer import Customer
from tests.sdk.petstore.models.order import Order
from tests.sdk.petstore.models.pet import Pet
from tests.sdk.petstore.models.tag import Tag
from tests.sdk.petstore.models.user import User
